/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyContract } from "./MyContract";
export type { Voting } from "./Voting";
export * as factories from "./factories";
export { MyContract__factory } from "./factories/MyContract__factory";
export { Voting__factory } from "./factories/Voting__factory";
